server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: SYSTEM-SERVICE

spring:
  application:
    name: SYSTEM-SERVICE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp16730aq4j29ys9y5o.mysql.rds.aliyuncs.com/java_test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: languohui
    password: languohui!@#$%^*()
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000

      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
mybatis-plus:
  mapper-locations: classpath*:com/languohui/lgh/mapper/*Mapper.xml
  type-aliases-package: com.languohui.lgh.domain,com.languohui.lgh.query

logging:
  level:
    com.languohui.lgh: debug